#!/usr/bin/env bash
# Creates a PID file, loops forever, and reacts to SIGTERM, SIGINT and SIGQUIT

echo "$$" > /var/run/myscript.pid

cleanup_and_exit() {
rm -f /var/run/myscript.pid
exit 0
}

trap 'echo "I hate the kill command"; cleanup_and_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup_and_exit' SIGQUIT

while true; do
echo "To infinity and beyond"
sleep 2
done
